### PR TITLE
OpenFF package structure

### PR DESCRIPTION
**Pull request by Yoshanuikabundi**
Reorganises the cookiecutter to produce the conventional OpenFF structure, with the `openff` implicit namespace package.

I think it works! But will be nice to see CI pass.

### CODE REVIEW

**Comment by Yoshanuikabundi** [comment]
I can't make heads or tails of this CI output :/

**Comment by lilyminium** [comment]
Ah yeah, it's not fantastic -- one thing could be commenting out the matrix of tests in the cookie/.github/ci so that multiple runners aren't dumping output at once.

Just from a quick glance I think renaming tests to _tests might be the issue -- the cookie is still trying to `pytest tests` (https://github.com/lilyminium/cookiecutter-openff/actions/runs/4740200894/jobs/8415768856?pr=4#step:8:2218) and conftest.py still imports the fixture file from `.tests`. I'm curious if that's the issue, so took the liberty of pushing to your branch (and commenting out the full matrix) to see.

**Comment by lilyminium** [comment]
Alright, the output's a lot easier to read now -- looks like the package isn't installing correctly since there's a ModuleNotFoundError (https://github.com/lilyminium/cookiecutter-openff/actions/runs/4770310349/jobs/8481454859#step:8:1286)

**Comment by Yoshanuikabundi** [comment]
@lilyminium Thanks for that! Magic. Is this now good to merge?

**Comment by lilyminium** [comment]
Ah yup, sorry for the delay!

**Pull request merged**
